<?php

use Illuminate\Database\Seeder;

class CommunesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
    	$communes = [
    		['id' => 1, 'name' => 'Arica', 'province_id' => 1],
            ['id' => 2, 'name' => 'Camarones', 'province_id' => 1],
            ['id' => 3, 'name' => 'General Lagos', 'province_id' => 2],
            ['id' => 4, 'name' => 'Putre', 'province_id' => 2],
            ['id' => 5, 'name' => 'Alto Hospicio', 'province_id' => 3],
            ['id' => 6, 'name' => 'Iquique', 'province_id' => 3],
            ['id' => 7, 'name' => 'Camiña', 'province_id' => 4],
            ['id' => 8, 'name' => 'Colchane', 'province_id' => 4],
            ['id' => 9, 'name' => 'Huara', 'province_id' => 4],
            ['id' => 10, 'name' => 'Pica', 'province_id' => 4],
            ['id' => 11, 'name' => 'Pozo Almonte', 'province_id' => 4],
            ['id' => 12, 'name' => 'Tocopilla', 'province_id' => 5],
            ['id' => 13, 'name' => 'María Elena', 'province_id' => 5],
            ['id' => 14, 'name' => 'Calama', 'province_id' => 6],
            ['id' => 15, 'name' => 'Ollague', 'province_id' => 6],
            ['id' => 16, 'name' => 'San Pedro de Atacama', 'province_id' => 6],
            ['id' => 17, 'name' => 'Antofagasta', 'province_id' => 7],
            ['id' => 18, 'name' => 'Mejillones', 'province_id' => 7],
            ['id' => 19, 'name' => 'Sierra Gorda', 'province_id' => 7],
            ['id' => 20, 'name' => 'Taltal', 'province_id' => 7],
            ['id' => 21, 'name' => 'Chañaral', 'province_id' => 8],
            ['id' => 22, 'name' => 'Diego de Almagro', 'province_id' => 8],
            ['id' => 23, 'name' => 'Copiapó', 'province_id' => 9],
            ['id' => 24, 'name' => 'Caldera', 'province_id' => 9],
            ['id' => 25, 'name' => 'Tierra Amarilla', 'province_id' => 9],
            ['id' => 26, 'name' => 'Vallenar', 'province_id' => 10],
            ['id' => 27, 'name' => 'Alto del Carmen', 'province_id' => 10],
            ['id' => 28, 'name' => 'Freirina', 'province_id' => 10],
            ['id' => 29, 'name' => 'Huasco', 'province_id' => 10],
            ['id' => 30, 'name' => 'La Serena', 'province_id' => 11],
            ['id' => 31, 'name' => 'Coquimbo', 'province_id' => 11],
            ['id' => 32, 'name' => 'Andacollo', 'province_id' => 11],
            ['id' => 33, 'name' => 'La Higuera', 'province_id' => 11],
            ['id' => 34, 'name' => 'Paihuano', 'province_id' => 11],
            ['id' => 35, 'name' => 'Vicuña', 'province_id' => 11],
            ['id' => 36, 'name' => 'Ovalle', 'province_id' => 12],
            ['id' => 37, 'name' => 'Combarbalá', 'province_id' => 12],
            ['id' => 38, 'name' => 'Monte Patria', 'province_id' => 12],
            ['id' => 39, 'name' => 'Punitaqui', 'province_id' => 12],
            ['id' => 40, 'name' => 'Río Hurtado', 'province_id' => 12],
            ['id' => 41, 'name' => 'Illapel', 'province_id' => 13],
            ['id' => 42, 'name' => 'Canela', 'province_id' => 13],
            ['id' => 43, 'name' => 'Los Vilos', 'province_id' => 13],
            ['id' => 44, 'name' => 'Salamanca', 'province_id' => 13],
            ['id' => 45, 'name' => 'La Ligua', 'province_id' => 14],
            ['id' => 46, 'name' => 'Cabildo', 'province_id' => 14],
            ['id' => 47, 'name' => 'Zapallar', 'province_id' => 14],
            ['id' => 48, 'name' => 'Papudo', 'province_id' => 14],
            ['id' => 49, 'name' => 'Petorca', 'province_id' => 14],
            ['id' => 50, 'name' => 'Los Andes', 'province_id' => 15],
            ['id' => 51, 'name' => 'San Esteban', 'province_id' => 15],
            ['id' => 52, 'name' => 'Calle Larga', 'province_id' => 15],
            ['id' => 53, 'name' => 'Rinconada', 'province_id' => 15],
            ['id' => 54, 'name' => 'San Felipe', 'province_id' => 16],
            ['id' => 55, 'name' => 'Llaillay', 'province_id' => 16],
            ['id' => 56, 'name' => 'Putaendo', 'province_id' => 16],
            ['id' => 57, 'name' => 'Santa María', 'province_id' => 16],
            ['id' => 58, 'name' => 'Catemu', 'province_id' => 16],
            ['id' => 59, 'name' => 'Panquehue', 'province_id' => 16],
            ['id' => 60, 'name' => 'Quillota', 'province_id' => 17],
            ['id' => 61, 'name' => 'La Cruz', 'province_id' => 17],
            ['id' => 62, 'name' => 'La Calera', 'province_id' => 17],
            ['id' => 63, 'name' => 'Nogales', 'province_id' => 17],
            ['id' => 64, 'name' => 'Hijuelas', 'province_id' => 17],
            ['id' => 65, 'name' => 'Valparaíso', 'province_id' => 18],   
            ['id' => 66, 'name' => 'Viña del Mar', 'province_id' => 18],
            ['id' => 67, 'name' => 'Concón', 'province_id' => 18],
            ['id' => 68, 'name' => 'Quintero', 'province_id' => 18],
            ['id' => 69, 'name' => 'Puchuncaví', 'province_id' => 18],
            ['id' => 70, 'name' => 'Casablanca', 'province_id' => 18],
            ['id' => 71, 'name' => 'Juan Fernández', 'province_id' => 18],
            ['id' => 72, 'name' => 'San Antonio', 'province_id' => 19],
            ['id' => 73, 'name' => 'Cartagena', 'province_id' => 19],
            ['id' => 74, 'name' => 'El Tabo', 'province_id' => 19],
            ['id' => 75, 'name' => 'El Quisco', 'province_id' => 19],
            ['id' => 76, 'name' => 'Algarrobo', 'province_id' => 19],
            ['id' => 77, 'name' => 'Santo Domingo', 'province_id' => 19],
            ['id' => 78, 'name' => 'Isla de Pascua', 'province_id' => 20],
            ['id' => 79, 'name' => 'Quilpué', 'province_id' => 21],
            ['id' => 80, 'name' => 'Limache', 'province_id' => 21],
            ['id' => 81, 'name' => 'Olmué', 'province_id' => 21],
            ['id' => 82, 'name' => 'Villa Alemana', 'province_id' => 21],
            ['id' => 83, 'name' => 'Colina', 'province_id' => 22],
            ['id' => 84, 'name' => 'Lampa', 'province_id' => 22],
            ['id' => 85, 'name' => 'Tiltil', 'province_id' => 22],
            ['id' => 86, 'name' => 'Santiago', 'province_id' => 23],
            ['id' => 87, 'name' => 'Vitacura', 'province_id' => 23],
            ['id' => 88, 'name' => 'San Ramón', 'province_id' => 23],
            ['id' => 89, 'name' => 'San Miguel', 'province_id' => 23],
            ['id' => 90, 'name' => 'San Joaquín', 'province_id' => 23],
            ['id' => 91, 'name' => 'Renca', 'province_id' => 23],
            ['id' => 92, 'name' => 'Recoleta', 'province_id' => 23],
            ['id' => 93, 'name' => 'Quinta Normal', 'province_id' => 23],
            ['id' => 94, 'name' => 'Quilicura', 'province_id' => 23],
            ['id' => 95, 'name' => 'Pudahuel', 'province_id' => 23],
            ['id' => 96, 'name' => 'Providencia', 'province_id' => 23],
            ['id' => 97, 'name' => 'Peñalolén', 'province_id' => 23],
            ['id' => 98, 'name' => 'Pedro Aguirre Cerda', 'province_id' => 23],
            ['id' => 99, 'name' => 'Ñuñoa', 'province_id' => 23],
            ['id' => 100, 'name' => 'Maipú', 'province_id' => 23],
            ['id' => 101, 'name' => 'Macul', 'province_id' => 23],
            ['id' => 102, 'name' => 'Lo Prado', 'province_id' => 23],
            ['id' => 103, 'name' => 'Lo Espejo', 'province_id' => 23],
            ['id' => 104, 'name' => 'Lo Barnechea', 'province_id' => 23],
            ['id' => 105, 'name' => 'Las Condes', 'province_id' => 23],
            ['id' => 106, 'name' => 'La Reina', 'province_id' => 23],
            ['id' => 107, 'name' => 'La Pintana', 'province_id' => 23],
            ['id' => 108, 'name' => 'La Granja', 'province_id' => 23],
            ['id' => 109, 'name' => 'La Florida', 'province_id' => 23],
            ['id' => 110, 'name' => 'La Cisterna', 'province_id' => 23],
            ['id' => 111, 'name' => 'Independencia', 'province_id' => 23],
            ['id' => 112, 'name' => 'Huechuraba', 'province_id' => 23],
            ['id' => 113, 'name' => 'Estación Central', 'province_id' => 23],
            ['id' => 114, 'name' => 'El Bosque', 'province_id' => 23],
            ['id' => 115, 'name' => 'Conchalí', 'province_id' => 23],
            ['id' => 116, 'name' => 'Cerro Navia', 'province_id' => 23],
            ['id' => 117, 'name' => 'Cerrillos', 'province_id' => 23],
            ['id' => 118, 'name' => 'Puente Alto', 'province_id' => 24],
            ['id' => 119, 'name' => 'San José de Maipo', 'province_id' => 24],
            ['id' => 120, 'name' => 'Pirque', 'province_id' => 24],
            ['id' => 121, 'name' => 'San Bernardo', 'province_id' => 25],
            ['id' => 122, 'name' => 'Buin', 'province_id' => 25],
            ['id' => 123, 'name' => 'Paine', 'province_id' => 25],
            ['id' => 124, 'name' => 'Calera de Tango', 'province_id' => 25],
            ['id' => 125, 'name' => 'Melipilla', 'province_id' => 26],
            ['id' => 126, 'name' => 'Alhué', 'province_id' => 26],
            ['id' => 127, 'name' => 'Curacaví', 'province_id' => 26],
            ['id' => 128, 'name' => 'María Pinto', 'province_id' => 26],
            ['id' => 129, 'name' => 'San Pedro', 'province_id' => 26],
            ['id' => 130, 'name' => 'Isla de Maipo', 'province_id' => 27],
            ['id' => 131, 'name' => 'El Monte', 'province_id' => 27],
            ['id' => 132, 'name' => 'Padre Hurtado', 'province_id' => 27],
            ['id' => 133, 'name' => 'Peñaflor', 'province_id' => 27],
            ['id' => 134, 'name' => 'Talagante', 'province_id' => 27],
            ['id' => 135, 'name' => 'Codegua', 'province_id' => 28],
            ['id' => 136, 'name' => 'Coínco', 'province_id' => 28],
            ['id' => 137, 'name' => 'Coltauco', 'province_id' => 28],
            ['id' => 138, 'name' => 'Doñihue', 'province_id' => 28],
            ['id' => 139, 'name' => 'Graneros', 'province_id' => 28],
            ['id' => 140, 'name' => 'Las Cabras', 'province_id' => 28],
            ['id' => 141, 'name' => 'Machalí', 'province_id' => 28],
            ['id' => 142, 'name' => 'Malloa', 'province_id' => 28],
            ['id' => 143, 'name' => 'Mostazal', 'province_id' => 28],
            ['id' => 144, 'name' => 'Olivar', 'province_id' => 28],
            ['id' => 145, 'name' => 'Peumo', 'province_id' => 28],
            ['id' => 146, 'name' => 'Pichidegua', 'province_id' => 28],
            ['id' => 147, 'name' => 'Quinta de Tilcoco', 'province_id' => 28],
            ['id' => 148, 'name' => 'Rancagua', 'province_id' => 28],
            ['id' => 149, 'name' => 'Rengo', 'province_id' => 28],
            ['id' => 150, 'name' => 'Requínoa', 'province_id' => 28],
            ['id' => 151, 'name' => 'San Vicente de Tagua Tagua', 'province_id' => 28],
            ['id' => 152, 'name' => 'Chépica', 'province_id' => 29],
            ['id' => 153, 'name' => 'Chimbarongo', 'province_id' => 29],
            ['id' => 154, 'name' => 'Lolol', 'province_id' => 29],
            ['id' => 155, 'name' => 'Nancagua', 'province_id' => 29],
            ['id' => 156, 'name' => 'Palmilla', 'province_id' => 29],
            ['id' => 157, 'name' => 'Peralillo', 'province_id' => 29],
            ['id' => 158, 'name' => 'Placilla', 'province_id' => 29],
            ['id' => 159, 'name' => 'Pumanque', 'province_id' => 29],
            ['id' => 160, 'name' => 'San Fernando', 'province_id' => 29],
            ['id' => 161, 'name' => 'Santa Cruz', 'province_id' => 29],
            ['id' => 162, 'name' => 'La Estrella', 'province_id' => 30],
            ['id' => 163, 'name' => 'Litueche', 'province_id' => 30],
            ['id' => 164, 'name' => 'Marchigüe', 'province_id' => 30],
            ['id' => 165, 'name' => 'Navidad', 'province_id' => 30],
            ['id' => 166, 'name' => 'Paredones', 'province_id' => 30],
            ['id' => 167, 'name' => 'Pichilemu', 'province_id' => 30],
            ['id' => 168, 'name' => 'Curicó', 'province_id' => 31],
            ['id' => 169, 'name' => 'Hualañé', 'province_id' => 31],
            ['id' => 170, 'name' => 'Licantén', 'province_id' => 31],
            ['id' => 171, 'name' => 'Molina', 'province_id' => 31],
            ['id' => 172, 'name' => 'Rauco', 'province_id' => 31],
            ['id' => 173, 'name' => 'Romeral', 'province_id' => 31],
            ['id' => 174, 'name' => 'Sagrada Familia', 'province_id' => 31],
            ['id' => 175, 'name' => 'Teno', 'province_id' => 31],
            ['id' => 176, 'name' => 'Vichuquén', 'province_id' => 31],
            ['id' => 177, 'name' => 'Talca', 'province_id' => 32],
            ['id' => 178, 'name' => 'San Clemente', 'province_id' => 32],
            ['id' => 179, 'name' => 'Pelarco', 'province_id' => 32],
            ['id' => 180, 'name' => 'Pencahue', 'province_id' => 32],
            ['id' => 181, 'name' => 'Maule', 'province_id' => 32],
            ['id' => 182, 'name' => 'San Rafael', 'province_id' => 32],
            ['id' => 183, 'name' => 'Curepto', 'province_id' => 33],
            ['id' => 184, 'name' => 'Constitución', 'province_id' => 32],
            ['id' => 185, 'name' => 'Empedrado', 'province_id' => 32],
            ['id' => 186, 'name' => 'Río Claro', 'province_id' => 32],
            ['id' => 187, 'name' => 'Linares', 'province_id' => 33],
            ['id' => 188, 'name' => 'San Javier', 'province_id' => 33],
            ['id' => 189, 'name' => 'Parral', 'province_id' => 33],
            ['id' => 190, 'name' => 'Villa Alegre', 'province_id' => 33],
            ['id' => 191, 'name' => 'Longaví', 'province_id' => 33],
            ['id' => 192, 'name' => 'Colbún', 'province_id' => 33],
            ['id' => 193, 'name' => 'Retiro', 'province_id' => 33],
            ['id' => 194, 'name' => 'Yerbas Buenas', 'province_id' => 33],
            ['id' => 195, 'name' => 'Cauquenes', 'province_id' => 34],
            ['id' => 196, 'name' => 'Chanco', 'province_id' => 34],
            ['id' => 197, 'name' => 'Pelluhue', 'province_id' => 34],
            ['id' => 198, 'name' => 'Bulnes', 'province_id' => 35],
            ['id' => 199, 'name' => 'Chillán', 'province_id' => 35],
            ['id' => 200, 'name' => 'Chillán Viejo', 'province_id' => 35],
            ['id' => 201, 'name' => 'El Carmen', 'province_id' => 35],
            ['id' => 202, 'name' => 'Pemuco', 'province_id' => 35],
            ['id' => 203, 'name' => 'Pinto', 'province_id' => 35],
            ['id' => 204, 'name' => 'Quillón', 'province_id' => 35],
            ['id' => 205, 'name' => 'San Ignacio', 'province_id' => 35],
            ['id' => 206, 'name' => 'Yungay', 'province_id' => 35],
            ['id' => 207, 'name' => 'Cobquecura', 'province_id' => 36],
            ['id' => 208, 'name' => 'Coelemu', 'province_id' => 36],
            ['id' => 209, 'name' => 'Ninhue', 'province_id' => 36],
            ['id' => 210, 'name' => 'Portezuelo', 'province_id' => 36],
            ['id' => 211, 'name' => 'Quirihue', 'province_id' => 36],
            ['id' => 212, 'name' => 'Ránquil', 'province_id' => 36],
            ['id' => 213, 'name' => 'Treguaco', 'province_id' => 36],
            ['id' => 214, 'name' => 'San Carlos', 'province_id' => 37],
            ['id' => 215, 'name' => 'Coihueco', 'province_id' => 37],
            ['id' => 216, 'name' => 'San Nicolás', 'province_id' => 37],
            ['id' => 217, 'name' => 'Ñiquén', 'province_id' => 37],
            ['id' => 218, 'name' => 'San Fabián', 'province_id' => 37],
            ['id' => 219, 'name' => 'Alto Biobío', 'province_id' => 38],
            ['id' => 220, 'name' => 'Antuco', 'province_id' => 38],
            ['id' => 221, 'name' => 'Cabrero', 'province_id' => 38],
            ['id' => 222, 'name' => 'Laja', 'province_id' => 38],
            ['id' => 223, 'name' => 'Los Ángeles', 'province_id' => 38],
            ['id' => 224, 'name' => 'Mulchén', 'province_id' => 38],
            ['id' => 225, 'name' => 'Nacimiento', 'province_id' => 38],
            ['id' => 226, 'name' => 'Negrete', 'province_id' => 38],
            ['id' => 227, 'name' => 'Quilaco', 'province_id' => 38],
            ['id' => 228, 'name' => 'Quilleco', 'province_id' => 38],
            ['id' => 229, 'name' => 'San Rosendo', 'province_id' => 38],
            ['id' => 230, 'name' => 'Santa Bárbara', 'province_id' => 38],
            ['id' => 231, 'name' => 'Tucapel', 'province_id' => 38],
            ['id' => 232, 'name' => 'Yumbel', 'province_id' => 38],
            ['id' => 233, 'name' => 'Concepción', 'province_id' => 39],
            ['id' => 234, 'name' => 'Coronel', 'province_id' => 39],
            ['id' => 235, 'name' => 'Chiguayante', 'province_id' => 39],
            ['id' => 236, 'name' => 'Florida', 'province_id' => 39],
            ['id' => 237, 'name' => 'Hualpén', 'province_id' => 39],
            ['id' => 238, 'name' => 'Hualqui', 'province_id' => 39],
            ['id' => 239, 'name' => 'Lota', 'province_id' => 39],
            ['id' => 240, 'name' => 'Penco', 'province_id' => 39],
            ['id' => 241, 'name' => 'San Pedro de La Paz', 'province_id' => 39],
            ['id' => 242, 'name' => 'Santa Juana', 'province_id' => 39],
            ['id' => 243, 'name' => 'Talcahuano', 'province_id' => 39],
            ['id' => 244, 'name' => 'Tomé', 'province_id' => 39],
            ['id' => 245, 'name' => 'Arauco', 'province_id' => 40],
            ['id' => 246, 'name' => 'Cañete', 'province_id' => 40],
            ['id' => 247, 'name' => 'Contulmo', 'province_id' => 40],
            ['id' => 248, 'name' => 'Curanilahue', 'province_id' => 40],
            ['id' => 249, 'name' => 'Lebu', 'province_id' => 40],
            ['id' => 250, 'name' => 'Los Álamos', 'province_id' => 40],
            ['id' => 251, 'name' => 'Tirúa', 'province_id' => 40],
            ['id' => 252, 'name' => 'Angol', 'province_id' => 41],
            ['id' => 253, 'name' => 'Collipulli', 'province_id' => 41],
            ['id' => 254, 'name' => 'Curacautín', 'province_id' => 41],
            ['id' => 255, 'name' => 'Ercilla', 'province_id' => 41],
            ['id' => 256, 'name' => 'Lonquimay', 'province_id' => 41],
            ['id' => 257, 'name' => 'Los Sauces', 'province_id' => 41],
            ['id' => 258, 'name' => 'Lumaco', 'province_id' => 41],
            ['id' => 259, 'name' => 'Purén', 'province_id' => 41],
            ['id' => 260, 'name' => 'Renaico', 'province_id' => 41],
            ['id' => 261, 'name' => 'Traiguén', 'province_id' => 41],
            ['id' => 262, 'name' => 'Victoria', 'province_id' => 41],
            ['id' => 263, 'name' => 'Temuco', 'province_id' => 42],
            ['id' => 264, 'name' => 'Carahue', 'province_id' => 42],
            ['id' => 265, 'name' => 'Cholchol', 'province_id' => 42],
            ['id' => 266, 'name' => 'Cunco', 'province_id' => 42],
            ['id' => 267, 'name' => 'Curarrehue', 'province_id' => 42],
            ['id' => 268, 'name' => 'Freire', 'province_id' => 42],
            ['id' => 269, 'name' => 'Galvarino', 'province_id' => 42],
            ['id' => 270, 'name' => 'Gorbea', 'province_id' => 42],
            ['id' => 271, 'name' => 'Lautaro', 'province_id' => 42],
            ['id' => 272, 'name' => 'Loncoche', 'province_id' => 42],
            ['id' => 273, 'name' => 'Melipeuco', 'province_id' => 42],
            ['id' => 274, 'name' => 'Nueva Imperial', 'province_id' => 42],
            ['id' => 275, 'name' => 'Padre Las Casas', 'province_id' => 42],
            ['id' => 276, 'name' => 'Perquenco', 'province_id' => 42],
            ['id' => 277, 'name' => 'Pitrufquén', 'province_id' => 42],
            ['id' => 278, 'name' => 'Pucón', 'province_id' => 42],
            ['id' => 279, 'name' => 'Saavedra', 'province_id' => 42],
            ['id' => 280, 'name' => 'Teodoro Schmidt', 'province_id' => 42],
            ['id' => 281, 'name' => 'Toltén', 'province_id' => 42],
            ['id' => 282, 'name' => 'Vilcún', 'province_id' => 42],
            ['id' => 283, 'name' => 'Villarrica', 'province_id' => 42],
            ['id' => 284, 'name' => 'Valdivia', 'province_id' => 43],
            ['id' => 285, 'name' => 'Corral', 'province_id' => 43],
            ['id' => 286, 'name' => 'Lanco', 'province_id' => 43],
            ['id' => 287, 'name' => 'Los Lagos', 'province_id' => 43],
            ['id' => 288, 'name' => 'Máfil', 'province_id' => 43],
            ['id' => 289, 'name' => 'Mariquina', 'province_id' => 43],
            ['id' => 290, 'name' => 'Paillaco', 'province_id' => 43],
            ['id' => 291, 'name' => 'Panguipulli', 'province_id' => 43],
            ['id' => 292, 'name' => 'La Unión', 'province_id' => 44],
            ['id' => 293, 'name' => 'Futrono', 'province_id' => 44],
            ['id' => 294, 'name' => 'Lago Ranco', 'province_id' => 44],
            ['id' => 295, 'name' => 'Río Bueno', 'province_id' => 44],
            ['id' => 297, 'name' => 'Osorno', 'province_id' => 45],
            ['id' => 298, 'name' => 'Puerto Octay', 'province_id' => 45],
            ['id' => 299, 'name' => 'Purranque', 'province_id' => 45],
            ['id' => 300, 'name' => 'Puyehue', 'province_id' => 45],
            ['id' => 301, 'name' => 'Río Negro', 'province_id' => 45],
            ['id' => 302, 'name' => 'San Juan de la Costa', 'province_id' => 45],
            ['id' => 303, 'name' => 'San Pablo', 'province_id' => 45],
            ['id' => 304, 'name' => 'Calbuco', 'province_id' => 46],
            ['id' => 305, 'name' => 'Cochamó', 'province_id' => 46],
            ['id' => 306, 'name' => 'Fresia', 'province_id' => 46],
            ['id' => 307, 'name' => 'Frutillar', 'province_id' => 46],
            ['id' => 308, 'name' => 'Llanquihue', 'province_id' => 46],
            ['id' => 309, 'name' => 'Los Muermos', 'province_id' => 46],
            ['id' => 310, 'name' => 'Maullín', 'province_id' => 46],
            ['id' => 311, 'name' => 'Puerto Montt', 'province_id' => 46],
            ['id' => 312, 'name' => 'Puerto Varas', 'province_id' => 46],
            ['id' => 313, 'name' => 'Ancud', 'province_id' => 47],
            ['id' => 314, 'name' => 'Castro', 'province_id' => 47],
            ['id' => 315, 'name' => 'Chonchi', 'province_id' => 47],
            ['id' => 316, 'name' => 'Curaco de Vélez', 'province_id' => 47],
            ['id' => 317, 'name' => 'Dalcahue', 'province_id' => 47],
            ['id' => 318, 'name' => 'Puqueldón', 'province_id' => 47],
            ['id' => 319, 'name' => 'Queilén', 'province_id' => 47],
            ['id' => 320, 'name' => 'Quellón', 'province_id' => 47],
            ['id' => 321, 'name' => 'Quemchi', 'province_id' => 47],
            ['id' => 322, 'name' => 'Quinchao', 'province_id' => 47],
            ['id' => 323, 'name' => 'Chaitén', 'province_id' => 48],
            ['id' => 324, 'name' => 'Futaleufú', 'province_id' => 48],
            ['id' => 325, 'name' => 'Hualaihué', 'province_id' => 48],
            ['id' => 326, 'name' => 'Palena', 'province_id' => 48],
            ['id' => 327, 'name' => 'Lago Verde', 'province_id' => 49],
            ['id' => 328, 'name' => 'Coihaique', 'province_id' => 49],
            ['id' => 329, 'name' => 'Aysén', 'province_id' => 50],
            ['id' => 330, 'name' => 'Cisnes', 'province_id' => 50],
            ['id' => 331, 'name' => 'Guaitecas', 'province_id' => 50],
            ['id' => 332, 'name' => 'Río Ibáñez', 'province_id' => 51],
            ['id' => 333, 'name' => 'Chile Chico', 'province_id' => 51],
            ['id' => 334, 'name' => 'Cochrane', 'province_id' => 52],
            ['id' => 335, 'name' => 'O\'Higgins', 'province_id' => 52],
            ['id' => 336, 'name' => 'Tortel', 'province_id' => 52],
            ['id' => 337, 'name' => 'Natales', 'province_id' => 53],
            ['id' => 338, 'name' => 'Torres del Paine', 'province_id' => 53],
            ['id' => 339, 'name' => 'Laguna Blanca', 'province_id' => 54],
            ['id' => 340, 'name' => 'Punta Arenas', 'province_id' => 54],
            ['id' => 341, 'name' => 'Río Verde', 'province_id' => 54],
            ['id' => 342, 'name' => 'San Gregorio', 'province_id' => 54],
            ['id' => 343, 'name' => 'Porvenir', 'province_id' => 55],
            ['id' => 344, 'name' => 'Primavera', 'province_id' => 55],
            ['id' => 345, 'name' => 'Timaukel', 'province_id' => 55],
            ['id' => 346, 'name' => 'Cabo de Hornos', 'province_id' => 56],
            ['id' => 347, 'name' => 'Antártica', 'province_id' => 56]
        ];
        DB::table('communes')->insert($communes);
    }
}
